Repository Automattic/jurassic.ninja, pull requests merged in 2018-02, with the labels that each got.

#91 Add filters and actions to allow for a more modular approach for feature addition
  jurassicninja.js
  lib/rest-api-stuff.php
  lib/stuff.php
Labels: enhancement

#81 Add docker config & update README
  .gitignore
  README.md
  docker-compose.yml
Labels: [Status] Needs Review, enhancement

#96 Add ability to launch sites with SSL
  jurassic.ninja.php
  lib/rest-api-stuff.php
  lib/serverpilot-stuff.php
  lib/settings-stuff.php
  lib/stuff.php
Labels: enhancement

#97 Define subdomain_multiste as default in rest endpoint
  lib/rest-api-stuff.php
Labels: bug
