Repository Automattic/jurassic.ninja, pull requests merged in 2019-01, with the labels that each got.

#158 add "chimuelo" to nouns list
  jurassic.ninja.php
  lib/words/nouns.txt
Labels: [type] Janitorial

#159 Add PHP 7.3 to the version matrix for shortlived sites and make sites default to PHP 7.2
  jurassic.ninja.php
  lib/serverpilot-stuff.php
  phpcs.xml
Labels: Feature, [Status] Ready to Merge, enhancement

#160 Add ability to launch with pregenerated content
  features/content.php
  jurassic.ninja.php
  lib/stuff.php
Labels: Feature, enhancement

#146 Adds tab indicator to the build page
  jurassic.ninja.php
  jurassicninja.js
Labels: enhancement

#161 Add ability to launch a site with WP Job Manager, WP Super Cache, and /or Crowdsignal.
  features/plugins.php
  jurassic.ninja.php
Labels: Feature
